name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Go environment
      uses: actions/setup-go@v5.0.1
      with:
        go-version: "1.21"
        go-version-file: src/go.mod
          
    
    - name: Build menucko binary
      run: make build
      working-directory: ./src
    
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
