name: 'Build,  publish  and deploy "menucko" to Azure'

on:
  push:
    branches: [ "main", "feature/github-action-build" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    name: Build and publish Docker image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build the Docker image
      run: docker build --file ./docker/Dockerfile --build-arg commit=${GITHUB_SHA} --tag rolandkister/menucko:latest  .

  styles:
    name: Minify and upload styles.css
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
        
    - name: Minify styles.css
      uses: nizarmah/auto-minify@v3
      with:
        directory: static/
        output: static-minified/

    - name: Rename minifies styles.min.css to styles.css
      run: ls -al static-minified; mv static-minified/styles.min.css static-minified/styles.css
     
    - name: Upload minified styles.css
      uses: LanceMcCarthy/Action-AzureBlobUpload@v2
      with:
        connection_string: ${{ secrets.BLOB_CONNECTION_STRING }}
        container_name: "$web"
        source_folder: static-minified/styles.css
        destination_folder: /
