# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy dotnet core project to Azure Function App - menucko

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'Source/Menucko/' # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '6.0.x' # set this to the dotnet version to use

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output --os linux
          popd

      - name: 'Install Leptonica and Tesseract'
        shell: bash
        run: |
          sudo apt install apt-transport-https
          sudo tee /etc/apt/sources.list.d/notesalexp.list<<EOF
          deb https://notesalexp.org/tesseract-ocr5/$(lsb_release -cs)/ $(lsb_release -cs) main
          EOF
          wget -O - https://notesalexp.org/debian/alexp_key.asc | sudo apt-key add -
          sudo apt update
          sudo apt install -y libleptonica-dev libtesseract-dev
          cp /usr/lib/x86_64-linux-gnu/libleptonica.so ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output/x64/libleptonica-1.82.0.so
          cp /usr/lib/x86_64-linux-gnu/libtesseract.so ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output/x64/tesseract50.so

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'menucko'
          slot-name: 'Production'
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_E81EE1EC55754C3DB2530CBAA47BEE0F }}
